# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c33497c5e4bbf06ff9d02b5c10b98188e829225e7ea25ad9815d54a93ab43a0fb9b13fb1cea404bc469da8e0ad2b282d73635e9731da5bcb958343e8dab50ba

test:
  secret_key_base: fc100ceb3ddf53b62122ad4f4181d25d2f4d88737058ed2f643861030d1f1cf024221f68d74a925e1c31b1c1219edd054cc1a042790d7ee740fb3795dc8dbafb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
